
__version__ = "$Revision: 1.1 $"

"""
$Log: cNetException.py,v $
Revision 1.1  2001/03/24 19:22:47  i10614
Initial revision

Revision 1.1  2001/03/17 15:01:21  mbauer
Initial release


"""

class versionError:
    """Wrong version of DOM

    raise this when a DOM is generated by an owl with another
    version than mine.

    """

    def __init__(self, value):
        self.value = value
    def __str__(self):
        return `self.value`


class domError:
    """unparseable DOM

    raise this when a DOM is not parseable.

    """

    def __init__(self, value):
        self.value = value
    def __str__(self):
        return `self.value`

