__version__ = "$Revision: 1.1 $"

"""
$Log: cAboutDataGrabber.py,v $
Revision 1.1  2001/03/24 19:22:56  i10614
Initial revision

Revision 1.2  2001/02/22 14:47:42  mbauer
new Gui-look implemented

Revision 1.1  2001/02/21 10:52:00  mbauer
initial release



"""
import pManager

class cAboutDataGrabber:
    """Responsible for displaying About-iOwl pages"""

    def __init__(self, cGuiRequestHandler):
        """Constructor"""
        self.cGuiRequestHandler = cGuiRequestHandler
        self.sAboutFileName = '../pGui/about.ht'

    def SetAboutFileName(self, name):
        """Set filename where to find about-page"""
        self.sAboutFileName = name

    def GetHtml(self, dParams):
        """Return complete HTML-page

        Since aboutfile is static, just load it from disc

        return string
        - beginning with tag <html>
        - ending with tag </html>

        http headers etc are generated by proxy!

        """

        # load aboutfile from disc
        aboutfile = open(self.sAboutFileName, 'r')

        # read aboutfile to string
        sContent = aboutfile.read()

        # get Header
        sHeader = self.cGuiRequestHandler.GetHeader('iOwl.net - About')

        # get Footer
        sFooter = self.cGuiRequestHandler.GetFooter()

        # Glue it
        sPage = sHeader + sContent + sFooter

        # return page and content-type
        return sPage, 'text/html'















##################################
if __name__=='__main__':
        # load helpfile from disc
        helpfile = open('../pGui/help.ht', 'r')

        # read helpfile to string
        sContent = helpfile.read()

        print sContent












