__version__ = "$Revision: 1.1 $"

"""
$Log: cLongtermRecommendationDataGrabber.py,v $
Revision 1.1  2001/03/24 19:22:59  i10614
Initial revision

Revision 1.2  2001/02/22 14:47:43  mbauer
new Gui-look implemented

Revision 1.1  2001/02/21 14:50:13  mbauer
initial release



"""
import pManager
import urlparse
import cJavaScriptTimer

class cLongtermRecommendationDataGrabber:
    """Get recommendations for all-time favorites"""

    def __init__(self, cGuiRequestHandler):
        """Constructor"""
        self.cGuiRequestHandler = cGuiRequestHandler


    def GetHtml(self, dParams):
        """Return complete HTML-page

        To allow the package pRecommendation to gather answers,
        start Query and return a page containing a java-script countdown.
        After countdown is finished, start a new request that
        forces pRecommendation to display its results.

        http headers etc are generated by proxy.

        dParams - empty dict

        return  -- string (<html>.....</html)

        """

        # time to wait till reload
        iSeconds = 20

        # get pRecommendationInterface
        cRecommendationInterface = pManager.manager.GetRecommendationInterface()

        # start request for Recommendations
        iReqID = cRecommendationInterface.GenerateLongtermRequest()

        # build url to load after timer finished
        sNewUrl = 'http://iowl/command?action=getrecommendations&id=%s&sUrl=%s' % (str(iReqID), 'longterm_browsing')

        # get javascript timer
        sScript, sFunction, sForm = cJavaScriptTimer.cJavaScriptTimer().GetTimer(iSeconds, sNewUrl)

        # get Header including timerscript
        sHeader = self.cGuiRequestHandler.GetHeader('iOwl.net - Waiting for Recommendations', sScript, sFunction)

        # get content
        sContent = """
                   <h1>Gathering recommendations</h1>
                   <p>
                   Please wait while iOwl.net gathers information for your request.
                   Time left: %s
                   seconds.
                   """ %sForm

        # get Footer
        sFooter = self.cGuiRequestHandler.GetFooter()

        # glue together
        sPage = sHeader + sContent + sFooter

        # return page and content-type
        return sPage, 'text/html'

