#!/bin/sh
# iOwl.net - install

DIR=`pwd`

if [ ! "`cat ~/.bash_profile | grep iowl.start`" ]; then
echo "" >> ~/.bash_profile;
echo cd "$DIR" >> ~/.bash_profile;
echo exec "$DIR"/iowl.start \& >> ~/.bash_profile;
echo "Adding iowl.start to ~/.bash_profile to start iOwl.net on every console login";
echo cd ~ >> ~/.bash_profile;
else echo "iowl.start is part of your ~/.bash_profile and starts iOwl.net on every console login";
fi

if [ ! "`cat ~/.bashrc | grep iowl.start`" ];then
echo "" >> ~/.bashrc;
echo cd "$DIR" >> ~/.bashrc;
echo exec "$DIR"/iowl.start \& >> ~/.bashrc;
echo "Adding iowl.start to ~/.bashrc to start iOwl.net on every X login";
echo cd ~ >> ~/.bashrc;
else echo "iowl.start is part of your ~/.bashrc and starts iOwl.net on every X login";
fi

exit 0
