
__version__ = "$Revision: 1.1 $"

"""
$Log: pRecommendationInterface.py,v $
Revision 1.1  2001/03/24 19:22:50  i10614
Initial revision

Revision 1.14  2001/02/22 23:20:43  a
fixed minor bug

Revision 1.13  2001/02/22 22:02:28  a
minor changes

Revision 1.12  2001/02/22 21:53:19  a
bug fixes for supporting history list

Revision 1.11  2001/02/22 15:18:32  a
giving recommendations to own owl from own clickstream

Revision 1.10  2001/02/22 15:13:52  a
owls gives recommendation to itself

Revision 1.9  2001/02/22 12:17:07  a
basic network functionality

Revision 1.8  2001/02/21 18:30:05  a
basic functions work

Revision 1.7  2001/02/21 16:03:50  a
minor changes

Revision 1.6  2001/02/21 13:57:16  mbauer
added import statement for urlparse

Revision 1.5  2001/02/21 13:21:24  a
cosmetic changes

Revision 1.4  2001/02/21 13:00:13  a
added methods for Gui

Revision 1.3  2001/02/19 19:20:05  a
added *Handler classes

Revision 1.2  2001/02/19 18:20:29  a
initial version

Revision 1.1  2001/02/18 22:32:48  a
initial version


"""
import urlparse
import pManager
import cRecommendationBuilder
import cRequestBuilder
import cRequest
import cAnswer


class pRecommendationInterface:

    """Recommendation class.
    
    This class is responsible for creating and answering request as well
    as compute recommendations from answers of other owls. A request
    can consist of 1..n URLs. If the user wants recommendations, request
    to other owls must be issued first. That is done in this class.

    """

    def __init__(self):
        """Constructor."""
        self.iTopList = 23
        self.RecBuilder = cRecommendationBuilder.cRecommendationBuilder()
        self.ReqBuilder = cRequestBuilder.cRequestBuilder()
        # returned rules from network, key is id
        self.dRules = {}


    def Start(self):
        """Kind of constructor."""
        print "start"


    def SetParam(self, sParameter, sValue):
        """Get config from pManagement.

        sParameter -- key
        sValue -- value

        """
        if (sParameter == 'toplist'):
            self.iTopList = sValue


    def Shutdown(self):
        """Kind of destructor."""
        print "shutdown"


    def GenerateSingleRequest(self, sUrl):
        """Generate a request and send it to network.

        sUrl -- Url to get recommendations for
        
        """
        tUrl = urlparse.urlparse(sUrl)
        el = self.ReqBuilder.DoRequest([tUrl,])

        #XXX just for the show
        # is only here to test recommendation of own owl w/o network
        # should be executed on other owls
        #id = ni.SendRequest(el)
        sId = '4711'
        self.SetRequest(el, sId)
        print 'SendRequest'

        # return to gui
        return sId


    def GenerateSessionRequest(self):
        """Generate a request and send it to network.

        return -- id

        """
        
        print "Getting session Recommendation for current session."

        csi = pManager.manager.GetClickstreamInterface()
        lUrls = []
        lClicks = csi.GetHistory()
        for click in lClicks:
            lUrls.append(click.GetUrl())

        el = self.ReqBuilder.DoRequest(lUrls)

        #XXX just for the show
        # is only here to test recommendation of own owl w/o network
        # should be executed on other owls
        #id = ni.SendRequest(el)
        sId = '4711'
        self.SetRequest(el, sId)
        print 'SendRequest'

        # return to gui
        return sId


    def GetRecommendations(self, sId):
        """Return a list with recommendations.

        This method is called from gui.

        id -- id gotten from network
        return -- list of clicks

        """
        if self.dRules.has_key(sId):
            lClicks = self.RecBuilder.BuildRecommendation(self.dRules[sId])
            del self.dRules[sId]
            return lClicks
        else:
            print 'NO RECOMMENDATIONS FOUND!'
            return None


    def SetRequest(self, reqEl, sId):
        """Incoming request from network layer.

        After receiving a request an answer must be issued to network with
        method SendRequest from pNetworkInterface.

        reqEl - element with request from other owl
        id -- unique id generated by network

        """
        print 'SetRequest'
        request = cRequest.cRequest()
        request.SetElement(reqEl)

        psi = pManager.manager.GetStatisticsInterface()
        lMatchingRules = psi.GetMatches(request.GetUrls())

        # XXX if lMatchingRules = NULL
        # don't send request

        if lMatchingRules:
            answer = cAnswer.cAnswer()
            answer.SetRules(lMatchingRules)

            answerEl = answer.GetElement()

            ni = pManager.manager.GetNetworkInterface()

            # XXX SetAnswer just for the show
            self.SetAnswer(answerEl, sId)
            # should only executed on other owls
            # ni.SendAnswer(answerEl, sId)


    def SetAnswer(self, answerEl, sId):
        """Incoming answer for a sent request from network layer.

        answer -- elements with answer from other owls
        id -- unique id of my request

        """
        print 'SetAnswer!'
        answer = cAnswer.cAnswer()
        answer.SetElement(answerEl)

        lAnswerRules = answer.GetRules()

        # with network, append, without don't append because only one
        # answer (from myself) is given
        # self.dRules[sId].append(lAnswerRules)
        self.dRules[sId] = lAnswerRules


#    def GenerateLongtermRequest(self):
#        """Generate a request and send it to network.
#
#        return -- id
#
#        """
#        id = 0
#        # print "id = send request to network"
#        return id

        
####################################################################
## TEST FUNCTIONS ##################################################

def test():
    """Built-in test method for this class."""
    
    print "none"
    

if __name__ == '__main__':
    test()
